# Generated by Django 2.1 on 2018-11-07 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('idRescatado', models.AutoField(primary_key=True, serialize=False)),
                ('fotoRescatado', models.ImageField(upload_to='fotos_rescatados')),
                ('nombreRescatado', models.CharField(max_length=20)),
                ('razaRescatado', models.CharField(max_length=20)),
                ('descripcionRescatado', models.TextField(max_length=80)),
                ('estadoRescatado', models.CharField(default='Rescatado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=30)),
                ('nombreCompleto', models.CharField(max_length=30)),
                ('direccionUsuario', models.CharField(max_length=30)),
                ('perfil', models.CharField(default='Adoptante', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
